# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eXGa1ak-Qc526GQEf08V9lLtR6B99wab
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
import joblib

train_df = pd.read_csv('train_data_cleaned.csv')
test_df = pd.read_csv('test_data_cleaned.csv')

X_train = train_df.drop(columns=['Price', 'ID'], errors='ignore')
y_train = train_df['Price']

X_test = test_df.drop(columns=['Price', 'ID'], errors='ignore')

X_train = pd.get_dummies(X_train, drop_first=True)
X_test = pd.get_dummies(X_test, drop_first=True)

X_train, X_test = X_train.align(X_test, join='left', axis=1, fill_value=0)

X_train = X_train.fillna(X_train.mean())
X_test = X_test.fillna(X_train.mean())

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

if 'Price' in test_df.columns:
    y_test = test_df['Price']
    print("MSE:", mean_squared_error(y_test, y_pred))
    print("R²:", r2_score(y_test, y_pred))

joblib.dump(model, 'linear_regression_model.pkl')
joblib.dump(scaler, 'scaler.pkl')

output = test_df.copy()
output['PredictedPrice'] = y_pred
output.to_csv('predictions.csv', index=False)

import zipfile
from google.colab import files

# الملفات اللي عايز تحملها
files_to_zip = ['linear_regression_model.pkl', 'predictions.csv']

# اسم ملف ZIP النهائي
zip_filename = 'project_files.zip'

# إنشاء ملف ZIP
with zipfile.ZipFile(zip_filename, 'w') as zipf:
    for file in files_to_zip:
        zipf.write(file)

# تحميل ملف ZIP واحد فيه كل الملفات
files.download(zip_filename)